name: pinlog
description: "Pin Route — Life Logging Diary"


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: ^3.11.4







dependencies:
  flutter:
    sdk: flutter

  
  
  cupertino_icons: ^1.0.8

  
  mapbox_maps_flutter: ^2.5.0
  latlong2: ^0.9.1

  
  flutter_map: ^7.0.2

  
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.4.0

  
  hive_flutter: ^1.1.0
  shared_preferences: ^2.3.4

  
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  path_provider: ^2.1.5

  
  package_info_plus: ^8.0.0
  uuid: ^4.5.1
  intl: ^0.19.0
  geolocator: ^13.0.4
  geocoding: ^3.0.0
  permission_handler: ^11.4.0

  
  flutter_svg: ^2.0.10+1
  vector_graphics: ^1.2.2

  
  app_links: ^7.0.0

  
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  supabase_flutter: ^2.9.1
  flutter_local_notifications: ^18.0.0

  
  share_plus: ^10.1.4

  
  http: ^1.2.0

  
  sign_in_with_apple: ^6.1.2
  crypto: ^3.0.6

  
  kakao_flutter_sdk_user: ^1.9.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  riverpod_generator: ^2.4.0





flutter:

  
  
  
  uses-material-design: true

  assets:
    - lib/img/Kyeonbookgoung.jpeg
    - lib/img/GwangWhamoon.jpeg
    - lib/img/Bookchone koreanvillage.webp
    - lib/img/잠실 롯데타워.png
    - lib/img/잠실 한강공원 .jpg
    - lib/img/뚝섬 한강공원.png
    - lib/img/성수동 카페거리.png
    - lib/img/강변북로 야경.png
    - lib/img/서울숲 산책로.png
    - lib/img/광장시장 육회골목.png
    - lib/img/을지로 노포.png
    - lib/img/성수 콘크리트.png
    - lib/img/홍대 연남동 골목 카페.png
    - lib/img/이태원 경리단길 야경.jpeg
    - lib/img/강남 코엑스 별마당 도서관.png
    - lib/img/한강 뚝섬 유원지.jpeg
    - lib/img/성수동 팝업 스토어.png
    - lib/img/성수동 블루보틀.png
    - lib/img/연남동 작은 카페.png
    - lib/img/망원동 골목 카페.png
    - lib/img/apple-inc-svgrepo-com.svg
    - lib/img/google-color-svgrepo-com.svg
    - lib/img/kakao-svgrepo-com.svg
    - lib/img/car-svgrepo-com.svg
    - lib/img/bus-svgrepo-com.svg
    - lib/img/walk-svgrepo-com.svg
    - lib/img/wind-svgrepo-com.svg
    - lib/img/sports/
    - lib/img/food/
    - lib/img/life/
    - lib/img/nature/
    - lib/img/emotion/
    - lib/img/place/
    - lib/img/flag/
    - lib/img/badge/
    - lib/img/ui/
    - lib/img/number/
    - lib/img/frame/

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
